"""Clean each source separately. Raw files are never rewritten.
Run: python clean_data.py --raw-dir data/raw --output-dir outputs
"""
import argparse
from pathlib import Path
import numpy as np
import pandas as pd
from common import save_json,fingerprint,require_unique,require_files
from settings import ROOT,FILES,VOCABULARY,USAGE_METRICS
REQUIRED={
 'customers':['customer_id','customer_name','customer_email','customer_age','customer_gender','industry','region','company_size','plan_type','account_created_date'],
 'tickets':['ticket_id','customer_name','customer_email','customer_age','customer_gender','product_purchased','date_of_purchase','ticket_type','ticket_subject','ticket_status','resolution','ticket_priority','ticket_channel','first_response_time','time_to_resolution','customer_satisfaction_rating'],
 'usage':['customer_id','product','month']+USAGE_METRICS}
DATES={'customers':{'account_created_date':'%Y-%m-%d'},'tickets':{'date_of_purchase':'%d-%m-%Y','first_response_time':'%d-%m-%Y %H:%M','time_to_resolution':'%d-%m-%Y %H:%M'},'usage':{'month':'%Y-%m'}}
NUMBERS={'customers':['customer_age'],'tickets':['ticket_id','customer_age','customer_satisfaction_rating'],'usage':USAGE_METRICS}

def clean_table(raw, name):
 d=raw.copy();d.columns=d.columns.str.strip().str.lower().str.replace(r'\s+','_',regex=True)
 missing=set(REQUIRED[name])-set(d.columns)
 if missing:raise ValueError(f'{name}: missing required columns: {sorted(missing)}')
 d['source_row']=np.arange(2,len(d)+2) # CSV physical row when no embedded line breaks.
 issues=[]
 def flag(column,mask,reason,action):
  mask=mask.fillna(False);key='flag_'+column+'_'+reason;d[key]=mask
  for idx in d.index[mask]:issues.append({'table':name,'source_row':int(d.at[idx,'source_row']),'column':column,'issue':reason,'action':action})
 for col in REQUIRED[name]:
  d[col]=d[col].astype('string').str.strip().replace('',pd.NA)
  if col in VOCABULARY:
   mapping={v.casefold():v for v in VOCABULARY[col]};normal=d[col].str.replace(r'\s+',' ',regex=True).str.casefold();mapped=normal.map(mapping)
   flag(col,d[col].notna()&mapped.isna(),'unrecognised_category','retained for review; no fuzzy remapping')
   d[col]=mapped.where(mapped.notna(),d[col])
 if 'customer_email' in d:d['customer_email']=d.customer_email.str.lower()
 # Duplicate records are flagged and retained. Key conflicts stop execution later.
 duplicate=d[REQUIRED[name]].duplicated(keep=False);flag('record',duplicate,'exact_duplicate','retained; key checks may block merge')
 for col in NUMBERS[name]:
  original=d[col];converted=pd.to_numeric(original,errors='coerce');bad=original.notna()&converted.isna()
  flag(col,bad,'invalid_numeric','set cleaned value missing; raw preserved')
  invalid=converted.notna()&(~np.isfinite(converted)|(converted<0)|(converted%1!=0))
  if col=='customer_satisfaction_rating':invalid=invalid|(converted.notna()&~converted.between(1,5))
  if col=='ticket_id':invalid=invalid|(converted.notna()&converted.lt(1))
  flag(col,invalid,'invalid_range','set cleaned value missing; raw preserved')
  d[col]=converted.mask(invalid)
 for col,fmt in DATES[name].items():
  original=d[col];converted=pd.to_datetime(original,format=fmt,errors='coerce')
  flag(col,original.notna()&converted.isna(),'invalid_date','set cleaned value missing; raw preserved');d[col]=converted
 if name=='usage':
  impossible=d.active_days.gt(d.month.dt.days_in_month)
  flag('active_days',impossible,'exceeds_calendar_days','set cleaned active_days missing; retain other usage fields');d.loc[impossible,'active_days']=np.nan
  d['month']=d.month.dt.strftime('%Y-%m')
 if name=='tickets':
  flag('timestamps',d.time_to_resolution.lt(d.first_response_time),'resolution_before_response','retain timestamps; do not calculate support durations')
  flag('customer_satisfaction_rating',d.customer_satisfaction_rating.isna(),'missing_outcome','retain as unknown; never impute')
  flag('customer_satisfaction_rating',d.customer_satisfaction_rating.notna()&d.ticket_status.ne('Closed'),'rating_on_nonclosed','retain and review')
  flag('resolution',d.ticket_status.eq('Closed')&d.resolution.isna(),'missing_closed_resolution','retain and review')
 return d,issues

def run(raw_dir=ROOT/'data/raw', output_dir=ROOT/'outputs'):
 raw_dir=Path(raw_dir);raw_dir.mkdir(parents=True,exist_ok=True)
 require_files([raw_dir/file for file in FILES.values()], 'Supply the original CSVs in this directory, or run python setup_project.py --data-zip /path/to/data.zip. Raw data is not generated by the pipeline.')
 raw_dir=Path(raw_dir);out=Path(output_dir);clean=out/'clean';clean.mkdir(parents=True,exist_ok=True);report=out/'reports';report.mkdir(exist_ok=True)
 frames={};issues=[];manifest={};columns=[];categories=[]
 for name,file in FILES.items():
  path=raw_dir/file;raw=pd.read_csv(path,dtype='string',keep_default_na=False);d,found=clean_table(raw,name);frames[name]=d;issues.extend(found)
  manifest[name]={'file':file,'sha256':fingerprint(path),'raw_rows':len(raw),'clean_rows':len(d)}
  for c in REQUIRED[name]:columns.append({'table':name,'column':c,'dtype':str(d[c].dtype),'rows':len(d),'missing':int(d[c].isna().sum()),'unique_nonmissing':int(d[c].nunique())})
  for c in d.select_dtypes(include=['string','object']).columns:
   if c in VOCABULARY or c in ['industry','region','company_size']:
    for value,count in d[c].value_counts(dropna=False).items():categories.append({'table':name,'column':c,'value':value,'rows':int(count)})
 pd.DataFrame(issues,columns=['table','source_row','column','issue','action']).to_csv(report/'data_quality_issues.csv',index=False)
 pd.DataFrame(columns).to_csv(report/'column_profile.csv',index=False);pd.DataFrame(categories).to_csv(report/'category_inventory.csv',index=False);save_json(report/'input_manifest.json',manifest)
 # Fail closed rather than choosing an arbitrary customer or duplicating tickets.
 require_unique(frames['customers'],['customer_id'],'customers');require_unique(frames['customers'],['customer_email'],'customer email')
 require_unique(frames['tickets'],['ticket_id'],'tickets');require_unique(frames['usage'],['customer_id','product','month'],'usage')
 for name,d in frames.items():d.to_csv(clean/(name+'.csv'),index=False)
 print('Cleaned rows:',{n:len(d) for n,d in frames.items()});return frames

if __name__=='__main__':
 p=argparse.ArgumentParser(description=__doc__);p.add_argument('--raw-dir',type=Path,default=ROOT/'data/raw');p.add_argument('--output-dir',type=Path,default=ROOT/'outputs');a=p.parse_args();run(a.raw_dir,a.output_dir)
